name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore GMAO.sln
      - name: Build
        run: dotnet build GMAO.sln --no-restore --configuration Release
      - name: Test unit
        run: dotnet test tests/Application.Tests/Application.Tests.csproj --no-build --no-restore --verbosity normal
      - name: Test integration
        run: dotnet test tests/Integration.Tests/Integration.Tests.csproj --no-build --no-restore --verbosity normal
